### ISSUE TITLE
UI: Make a hero section

### ISSUE THREAD

**Issue by siwamsingh** [dscnsec/Stake-frontend-clone#10]
## Description
make a hero section same as the one in the official stake website

## Task
- Initialize HeroSection.jsx in `src/components/HeroSection` directory ( ⚠️ NOTE: If the components and HeroSection folders haven't been created yet, please go ahead and create them..)
- **Dont** make the nav bar ot the sidebar they are for other Issue.
- For the two images take a screen shot and crop the image and use them. Or inspect them to use their link. Choice is up to you.

## Implementation 🔽
![WhatsApp Image 2024-10-22 at 12 51 09 PM](https://github.com/user-attachments/assets/fb916a9f-2b55-4c84-95a2-2e0b837f5889)

**Comment by dakshsinghrathore** [comment]
Hey @yashwanthvarma18 If you've wrapped up the previous issues, it'd be awesome if you could take a look at this one. Really appreciating your enthusiasm with the OS contributions! Also, just a heads-up: the top contributor in this repo will be getting some swag, so it’d be great to see you go for it!

**Comment by yashwanthvarma18** [comment]
@dakshsinghrathore Sure I will send a PR tomorrow
