### ISSUE TITLE
Docs: Updating Readme.md

### ISSUE THREAD

**Issue by trinetra110** [dscnsec/Stake-frontend-clone#3]
## Description

Giving proper structure to Readme.md and adding banner for hacktoberfest, badges, emoji's, etc. to get a clear understanding of the project and to attract Contributors to contribute in this project.

## Additional note

Please add "hacktoberfest" level to this issue.

**Comment by dakshsinghrathore** [comment]
Kindly omit addition of badges, emojis will work also add "[all-contributors](https://github.com/all-contributors/all-contributors)"

**Comment by dakshsinghrathore** [comment]
@trinetra110 Also add the guide on how to fireup the project locally like this ⬇️ 

![image](https://github.com/user-attachments/assets/e62e0918-94c7-44c0-a914-eb02e063cd3d)

**Comment by dakshsinghrathore** [comment]
# Mention this note for contributors to understand the structure we are following in this clone project

## Component-Based Structure

We use a **component-based structure** with React, keeping UI elements modular and reusable. All UI components should go in the `src/components/ui/` folder to maintain consistency and organization.

### Contributor Guidelines:
- Ensure components are reusable across the app.
- Place components logically under `ui/` (e.g., forms, buttons, etc.).
- Keep components focused on a single task for simplicity and reusability.

@trinetra110

**Comment by trinetra110** [comment]
> Kindly omit addition of badges, emojis will work also add "[all-contributors](https://github.com/all-contributors/all-contributors)"

@dakshsinghrathore The all-contributors bot can be added by the repo owner/mainter I guess ? If it can be added by a contributor, please tell me how, I'll try it.

**Comment by dakshsinghrathore** [comment]
@trinetra110 https://github.com/ekreative/react-native-braintree/issues/43

**Comment by trinetra110** [comment]
@dakshsinghrathore Will do, thanks !

**Comment by dakshsinghrathore** [comment]
@trinetra110 Kindly add the readme first, it is of utmost priority at this moment, contributors bot can be added later too.

**Comment by trinetra110** [comment]
Ok almost done.
