### ISSUE TITLE
feat: Add Tailwind CSS

### ISSUE THREAD

**Issue by dakshsinghrathore** [dscnsec/Stake-frontend-clone#4]
https://tailwindcss.com/docs/guides/vite

FOLLOW THE ABOVE DOC TO INSTALL TAILWIND IN THIS PROJECT.

**Comment by Muhammadahmedanis** [comment]
Assign this issue so I can fix it

**Comment by Vaishali785** [comment]
Hi @dakshsinghrathore , I'd like to work on this task. Please assign it to me.

**Comment by ry44444n** [comment]
is it fixed already?

**Comment by dakshsinghrathore** [comment]
@ry44444n No, you can create a PR straightaway if you want to.

**Comment by Vaishali785** [comment]
Hi @ry44444n  @dakshsinghrathore , I've fixed this issue. @dakshsinghrathore  please check it once, if any changes are required just let me know.
