### ISSUE TITLE
Feat: Add CI/CD Workflow for enabling linting.

### ISSUE THREAD

**Issue by dakshsinghrathore** [dscnsec/Stake-frontend-clone#7]
## Description
Setup Github Actions bot of `ESlint` for PR code linting. We aim to run [ESLint](https://eslint.org/) in our CI/CD pipeline to automatically check for coding style issues and potential errors.

## Tasks
- Create a new YAML file for the linting workflow in the directory `.github/workflows/` . You can name it `lint.yml` 
- ⚠️ Make sure the yml code has apt `node-version` .

## Implementation Eg. ⬇️ 

![https___dev-to-uploads s3 amazonaws com_i_5h3i7hednybtoxyraiao](https://github.com/user-attachments/assets/71907f83-747e-4294-8216-27e87b962e4e)

**Comment by KrinsKumar** [comment]
Hey can I work on this? If yes please assign this to me!!

**Comment by dakshsinghrathore** [comment]
@KrinsKumar assigned.

**Comment by KrinsKumar** [comment]
Can we close this issue and mark it as `hacktoberfest-accepted`?
